// ─── HYROX SEASON 9 EVENT CALENDAR ──────────────────────────────────────────
// Status: 'past' | 'live' | 'upcoming'
// mapImg: direct image URL to venue map (JPG/PNG) — null if none known
// waves: array of { day, category, time } — day: 1 or 2
// venueUrl: official event page

const HYROX_EVENTS = [
  {
    id: 'hamburg-25',
    city: 'Hamburg',
    country: 'Germany',
    flag: '🇩🇪',
    venue: 'Hamburg Messe',
    date: '2025-10-03',
    dateLabel: '3–5 Oct 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-hamburg/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles Women', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '12:00' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Mixed Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Pro Women', time: '13:00' },
      { day: 2, category: 'HYROX Pro Men', time: '14:00' },
    ],
  },
  {
    id: 'manchester-25',
    city: 'Manchester',
    country: 'United Kingdom',
    flag: '🇬🇧',
    venue: 'Manchester Central',
    date: '2025-10-18',
    dateLabel: '18–19 Oct 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-manchester/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles', time: '11:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Pro Women', time: '12:00' },
      { day: 2, category: 'HYROX Pro Men', time: '13:00' },
    ],
  },
  {
    id: 'edinburgh-25',
    city: 'Edinburgh',
    country: 'United Kingdom',
    flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    venue: 'Royal Highland Centre',
    date: '2025-11-01',
    dateLabel: '1–2 Nov 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-edinburgh/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Doubles', time: '11:30' },
    ],
  },
  {
    id: 'milan-25',
    city: 'Milan',
    country: 'Italy',
    flag: '🇮🇹',
    venue: 'Allianz MiCo',
    date: '2025-11-08',
    dateLabel: '8–9 Nov 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-milan/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles', time: '11:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Pro Women', time: '12:00' },
      { day: 2, category: 'HYROX Pro Men', time: '13:00' },
    ],
  },
  {
    id: 'singapore-25',
    city: 'Singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    venue: 'Singapore Expo',
    date: '2025-11-15',
    dateLabel: '15–16 Nov 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-singapore/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Doubles', time: '11:30' },
    ],
  },
  {
    id: 'frankfurt-25',
    city: 'Frankfurt',
    country: 'Germany',
    flag: '🇩🇪',
    venue: 'Messe Frankfurt',
    date: '2025-11-22',
    dateLabel: '22–23 Nov 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-frankfurt/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles Women', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '12:00' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Mixed Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Pro Women', time: '13:00' },
      { day: 2, category: 'HYROX Pro Men', time: '14:00' },
    ],
  },
  {
    id: 'dubai-25',
    city: 'Dubai',
    country: 'UAE',
    flag: '🇦🇪',
    venue: 'Dubai World Trade Centre',
    date: '2025-12-05',
    dateLabel: '5–6 Dec 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-dubai/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '07:00' },
      { day: 1, category: 'HYROX Men', time: '08:30' },
      { day: 1, category: 'HYROX Doubles', time: '10:30' },
      { day: 2, category: 'HYROX Women', time: '07:00' },
      { day: 2, category: 'HYROX Men', time: '08:30' },
      { day: 2, category: 'HYROX Pro Women', time: '11:00' },
      { day: 2, category: 'HYROX Pro Men', time: '12:00' },
    ],
  },
  {
    id: 'melbourne-25',
    city: 'Melbourne',
    country: 'Australia',
    flag: '🇦🇺',
    venue: 'Melbourne Convention & Exhibition Centre',
    date: '2025-12-13',
    dateLabel: '13–14 Dec 2025',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-melbourne/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Doubles', time: '11:30' },
    ],
  },
  {
    id: 'berlin-26',
    city: 'Berlin',
    country: 'Germany',
    flag: '🇩🇪',
    venue: 'Messe Berlin',
    date: '2026-02-21',
    dateLabel: '21–22 Feb 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-berlin/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles Women', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '12:00' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Mixed Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Pro Women', time: '13:00' },
      { day: 2, category: 'HYROX Pro Men', time: '14:00' },
    ],
  },
  {
    id: 'madrid-26',
    city: 'Madrid',
    country: 'Spain',
    flag: '🇪🇸',
    venue: 'IFEMA Madrid',
    date: '2026-03-07',
    dateLabel: '7–8 Mar 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-madrid/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles', time: '11:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Pro Women', time: '12:00' },
      { day: 2, category: 'HYROX Pro Men', time: '13:00' },
    ],
  },
  {
    id: 'sydney-26',
    city: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    venue: 'ICC Sydney',
    date: '2026-03-14',
    dateLabel: '14–15 Mar 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-sydney/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Doubles', time: '11:30' },
    ],
  },
  {
    id: 'riga-26',
    city: 'Riga',
    country: 'Latvia',
    flag: '🇱🇻',
    venue: 'Riga Arena',
    date: '2026-03-21',
    dateLabel: '21–22 Mar 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-riga/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles Women', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '12:00' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Mixed Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Pro Women', time: '13:00' },
      { day: 2, category: 'HYROX Pro Men', time: '14:00' },
    ],
  },
  {
    id: 'cologne-26',
    city: 'Cologne',
    country: 'Germany',
    flag: '🇩🇪',
    venue: 'Koelnmesse',
    date: '2026-04-16',
    dateLabel: '16–19 Apr 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-cologne-2026/',
    mapImg: null,
    waves: [],
  },
  {
    id: 'london-26',
    city: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    venue: 'ExCeL London',
    date: '2026-04-18',
    dateLabel: '18–19 Apr 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-london/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '08:00' },
      { day: 1, category: 'HYROX Men', time: '09:30' },
      { day: 1, category: 'HYROX Doubles Women', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '12:00' },
      { day: 2, category: 'HYROX Women', time: '08:00' },
      { day: 2, category: 'HYROX Men', time: '09:30' },
      { day: 2, category: 'HYROX Mixed Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Pro Women', time: '13:00' },
      { day: 2, category: 'HYROX Pro Men', time: '14:00' },
    ],
  },
  {
    id: 'chicago-26',
    city: 'Chicago',
    country: 'USA',
    flag: '🇺🇸',
    venue: 'Donald E. Stephens Convention Center',
    date: '2026-05-02',
    dateLabel: '2–3 May 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-chicago/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '07:30' },
      { day: 1, category: 'HYROX Men', time: '09:00' },
      { day: 1, category: 'HYROX Doubles', time: '11:00' },
      { day: 2, category: 'HYROX Women', time: '07:30' },
      { day: 2, category: 'HYROX Men', time: '09:00' },
      { day: 2, category: 'HYROX Pro Women', time: '11:30' },
      { day: 2, category: 'HYROX Pro Men', time: '12:30' },
    ],
  },
  {
    id: 'toronto-26',
    city: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    venue: 'Enercare Centre',
    date: '2026-05-16',
    dateLabel: '16–17 May 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-toronto/',
    mapImg: null,
    waves: [
      { day: 1, category: 'HYROX Women', time: '07:30' },
      { day: 1, category: 'HYROX Men', time: '09:00' },
      { day: 2, category: 'HYROX Women', time: '07:30' },
      { day: 2, category: 'HYROX Men', time: '09:00' },
      { day: 2, category: 'HYROX Doubles', time: '11:00' },
    ],
  },
  {
    id: 'new-york-26',
    city: 'New York',
    country: 'USA',
    flag: '🇺🇸',
    venue: 'Javits Center',
    date: '2026-05-28',
    dateLabel: '28 May – 7 Jun 2026',
    status: 'past',
    venueUrl: 'https://hyrox.com/event/hyrox-new-york-2026/',
    mapImg: null,
    waves: [],
  },
  {
    id: 'buenos-aires-26',
    city: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    venue: 'La Rural',
    date: '2026-06-13',
    dateLabel: '13 Jun 2026',
    status: 'upcoming', ticketsOnSale: false,
    venueUrl: 'https://hyrox.com/event/hyrox-buenos-aires/',
    mapImg: 'maps/s9/buenos-aires-venue-map.pdf',
    mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'HYROX Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'HYROX Doubles Men', time: '11:00' },
      { day: 1, category: 'HYROX Doubles Women Pro', time: '12:40' },
      { day: 1, category: 'HYROX Women Pro', time: '12:50' },
      { day: 1, category: 'HYROX Doubles Women', time: '13:30' },
      { day: 1, category: 'HYROX Women / Adaptive Women', time: '14:50' },
      { day: 1, category: 'HYROX Doubles Mixed', time: '16:30' },
      { day: 1, category: 'HYROX Doubles Men Pro', time: '18:50' },
      { day: 1, category: 'HYROX Men Pro', time: '19:20' },
      { day: 1, category: "HYROX Men's Relay", time: '20:30' },
      { day: 1, category: 'HYROX Mixed Relay', time: '20:40' },
      { day: 1, category: "HYROX Women's Relay", time: '20:50' },
    ],
  },
  {
    id: 'world-champs-26',
    city: 'Stockholm',
    country: 'Sweden',
    flag: '🇸🇪',
    venue: 'Strawberry Arena',
    date: '2026-06-18',
    dateLabel: '18–21 Jun 2026',
    status: 'upcoming', ticketsOnSale: true,
    isChampionship: true,
    venueUrl: 'https://hyrox.com/event/puma-hyrox-world-championships-stockholm/',
    mapImg: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Elite 15 Women', time: '19:00' },
      { day: 1, category: 'Elite 15 Men', time: '20:30' },
      { day: 2, category: 'HYROX Pro Women', time: '07:30' },
      { day: 2, category: 'HYROX Pro Men', time: '12:05' },
      { day: 2, category: 'Elite 15 Pro Doubles Women', time: '20:20' },
      { day: 2, category: 'Elite 15 Pro Doubles Men', time: '21:35' },
      { day: 3, category: 'HYROX Pro Doubles Men', time: '07:30' },
      { day: 3, category: 'HYROX Pro Doubles Women', time: '12:25' },
      { day: 4, category: 'HYROX Doubles Mixed', time: '07:30' },
      { day: 4, category: 'Adaptive Invitational Women', time: '14:40' },
      { day: 4, category: 'Adaptive Invitational Men', time: '16:30' },
      { day: 4, category: 'Mixed Relay Invitational', time: '19:45' },
    ],
  },
];

// ─── HYROX SEASON 8 EVENT CALENDAR (2024 – 2025) ────────────────────────────
// All events are historical (past). Wave times not stored — results on hyrox.com.
const HYROX_S8_EVENTS = [
  {
    id: 's8-hamburg',
    city: 'Hamburg', country: 'Germany', flag: '🇩🇪',
    venue: 'Barclays Arena', date: '2024-10-05',
    dateLabel: '4–6 Oct 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/intersport-hyrox-hamburg/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-edinburgh',
    city: 'Edinburgh', country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    venue: 'Royal Highland Centre', date: '2024-11-02',
    dateLabel: '2–3 Nov 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-edinburgh/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-manchester',
    city: 'Manchester', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    venue: 'AO Arena', date: '2024-11-09',
    dateLabel: '9–10 Nov 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-manchester/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-milan',
    city: 'Milan', country: 'Italy', flag: '🇮🇹',
    venue: 'Allianz MiCo', date: '2025-01-11',
    dateLabel: '11–12 Jan 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-milan/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-singapore',
    city: 'Singapore', country: 'Singapore', flag: '🇸🇬',
    venue: 'Singapore Expo', date: '2025-01-25',
    dateLabel: '25–26 Jan 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/aia-hyrox-singapore/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-frankfurt',
    city: 'Frankfurt', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Frankfurt', date: '2025-02-15',
    dateLabel: '15–16 Feb 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/fitness-first-hyrox-frankfurt/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-dubai',
    city: 'Dubai', country: 'UAE', flag: '🇦🇪',
    venue: 'Dubai World Trade Centre', date: '2025-03-01',
    dateLabel: '1–2 Mar 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-dubai/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-melbourne',
    city: 'Melbourne', country: 'Australia', flag: '🇦🇺',
    venue: 'Melbourne Convention Centre', date: '2025-03-07',
    dateLabel: '7–9 Mar 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-melbourne/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-berlin',
    city: 'Berlin', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Berlin', date: '2025-03-22',
    dateLabel: '22–23 Mar 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-berlin/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-madrid',
    city: 'Madrid', country: 'Spain', flag: '🇪🇸',
    venue: 'IFEMA Madrid', date: '2025-04-05',
    dateLabel: '5–6 Apr 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-madrid/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-sydney',
    city: 'Sydney', country: 'Australia', flag: '🇦🇺',
    venue: 'ICC Sydney', date: '2025-04-25',
    dateLabel: '25–27 Apr 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/byd-hyrox-sydney/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-riga',
    city: 'Riga', country: 'Latvia', flag: '🇱🇻',
    venue: 'Riga Arena', date: '2025-05-03',
    dateLabel: '3–4 May 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-riga/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-london',
    city: 'London', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    venue: 'Olympia London', date: '2025-05-17',
    dateLabel: '17–18 May 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-london-excel/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-chicago',
    city: 'Chicago', country: 'USA', flag: '🇺🇸',
    venue: 'McCormick Place', date: '2025-05-17',
    dateLabel: '17–18 May 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-chicago/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-toronto',
    city: 'Toronto', country: 'Canada', flag: '🇨🇦',
    venue: 'Enercare Centre', date: '2025-05-31',
    dateLabel: '31 May–1 Jun 2025', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/goodlife-hyrox-toronto/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's8-nice-wc',
    city: 'Nice', country: 'France', flag: '🇫🇷',
    venue: 'Acropolis Nice', date: '2025-06-12',
    dateLabel: '12–15 Jun 2025', status: 'past', isChampionship: true,
    venueUrl: 'https://hyrox.com/event/puma-hyrox-world-championships-nice/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
];

// ─── HYROX SEASON 7 EVENT CALENDAR (2023 – 2024) ────────────────────────────
const HYROX_S7_EVENTS = [
  {
    id: 's7-hamburg',
    city: 'Hamburg', country: 'Germany', flag: '🇩🇪',
    venue: 'Barclays Arena', date: '2023-10-07',
    dateLabel: '7–8 Oct 2023', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/intersport-hyrox-hamburg/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-edinburgh',
    city: 'Edinburgh', country: 'Scotland', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    venue: 'Royal Highland Centre', date: '2023-11-04',
    dateLabel: '4–5 Nov 2023', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-edinburgh/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-manchester',
    city: 'Manchester', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    venue: 'AO Arena', date: '2023-11-11',
    dateLabel: '11–12 Nov 2023', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-manchester/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-milan',
    city: 'Milan', country: 'Italy', flag: '🇮🇹',
    venue: 'Allianz MiCo', date: '2024-01-13',
    dateLabel: '13–14 Jan 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-milan/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-singapore',
    city: 'Singapore', country: 'Singapore', flag: '🇸🇬',
    venue: 'Singapore Expo', date: '2024-02-03',
    dateLabel: '3–4 Feb 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/aia-hyrox-singapore/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-frankfurt',
    city: 'Frankfurt', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Frankfurt', date: '2024-02-17',
    dateLabel: '17–18 Feb 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/fitness-first-hyrox-frankfurt/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-dubai',
    city: 'Dubai', country: 'UAE', flag: '🇦🇪',
    venue: 'Dubai World Trade Centre', date: '2024-03-02',
    dateLabel: '2–3 Mar 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-dubai/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-melbourne',
    city: 'Melbourne', country: 'Australia', flag: '🇦🇺',
    venue: 'Melbourne Convention Centre', date: '2024-03-08',
    dateLabel: '8–10 Mar 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-melbourne/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-berlin',
    city: 'Berlin', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Berlin', date: '2024-03-16',
    dateLabel: '16–17 Mar 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-berlin/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-madrid',
    city: 'Madrid', country: 'Spain', flag: '🇪🇸',
    venue: 'IFEMA Madrid', date: '2024-04-06',
    dateLabel: '6–7 Apr 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-madrid/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-sydney',
    city: 'Sydney', country: 'Australia', flag: '🇦🇺',
    venue: 'ICC Sydney', date: '2024-04-19',
    dateLabel: '19–21 Apr 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/byd-hyrox-sydney/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-london',
    city: 'London', country: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    venue: 'Olympia London', date: '2024-05-04',
    dateLabel: '4–5 May 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-london-excel/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-chicago',
    city: 'Chicago', country: 'USA', flag: '🇺🇸',
    venue: 'McCormick Place', date: '2024-05-11',
    dateLabel: '11–12 May 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-chicago/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-toronto',
    city: 'Toronto', country: 'Canada', flag: '🇨🇦',
    venue: 'Enercare Centre', date: '2024-05-25',
    dateLabel: '25–26 May 2024', status: 'past', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/goodlife-hyrox-toronto/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's7-nice-wc',
    city: 'Nice', country: 'France', flag: '🇫🇷',
    venue: 'Acropolis Nice', date: '2024-06-13',
    dateLabel: '13–15 Jun 2024', status: 'past', isChampionship: true,
    venueUrl: 'https://hyrox.com/event/puma-hyrox-world-championships-nice/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
];

// ─── HYROX SEASON 10 EVENT CALENDAR (2026 – 2027) ───────────────────────────
const HYROX_S10_EVENTS = [
  {
    id: 's10-jakarta',
    city: 'Jakarta', country: 'Indonesia', flag: '🇮🇩',
    venue: 'Nusantara International Convention Exhibition (NICE)', date: '2026-06-27',
    dateLabel: '27–28 Jun 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-jakarta/',
    mapImg: 'https://hyrox.com/wp-content/uploads/2026/06/ID-JKT-Floor-Plan_Bilingual.pdf',
    mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open (incl. Adaptive)', time: '09:00–13:40' },
      { day: 1, category: 'Doubles Women Pro', time: '14:10–14:20' },
      { day: 1, category: 'Women Pro', time: '14:30–14:40' },
      { day: 1, category: 'Doubles Mixed', time: '15:10–18:20' },
      { day: 1, category: 'Doubles Men Pro', time: '19:00–19:30' },
      { day: 1, category: 'Men Pro', time: '19:40–20:10' },
      { day: 2, category: 'Doubles Women Open', time: '09:00–12:10' },
      { day: 2, category: 'Women Open (incl. Adaptive)', time: '12:20–13:50' },
      { day: 2, category: 'Doubles Men Open', time: '14:30–17:50' },
      { day: 2, category: 'Relay Men', time: '18:30–18:40' },
      { day: 2, category: 'Relay Mixed', time: '19:00–19:40' },
      { day: 2, category: 'Relay Women', time: '20:00–20:20' },
    ],
  },
  {
    id: 's10-sydney',
    city: 'Sydney', country: 'Australia', flag: '🇦🇺',
    venue: 'Sydney Showground, Sydney Olympic Park', date: '2026-07-01',
    dateLabel: '1–5 Jul 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-sydney/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-hangzhou',
    city: 'Hangzhou', country: 'China', flag: '🇨🇳',
    venue: 'Hangzhou International Expo Center – Hall 4D', date: '2026-07-04',
    dateLabel: '4–5 Jul 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-hangzhou/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00–13:10' },
      { day: 1, category: 'Doubles Women Pro', time: '13:30–14:00' },
      { day: 1, category: 'Women Pro', time: '14:10–14:40' },
      { day: 1, category: 'Doubles Mixed', time: '15:00–17:50' },
      { day: 1, category: 'Doubles Men Pro', time: '18:20–19:10' },
      { day: 1, category: 'Men Pro', time: '19:20–20:30' },
      { day: 2, category: 'Doubles Women', time: '08:00–10:40' },
      { day: 2, category: 'Women Open', time: '11:00–13:20' },
      { day: 2, category: 'Doubles Men', time: '13:50–17:00' },
      { day: 2, category: 'Relay Men', time: '17:30–18:05' },
      { day: 2, category: 'Relay Mixed', time: '18:25–19:35' },
      { day: 2, category: 'Relay Women', time: '19:55–20:30' },
    ],
  },
  {
    id: 's10-abu-dhabi',
    city: 'Abu Dhabi', country: 'UAE', flag: '🇦🇪',
    venue: 'TBC', date: '2026-07-15',
    dateLabel: 'Date coming soon', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-abu-dhabi/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-delhi',
    city: 'Delhi', country: 'India', flag: '🇮🇳',
    venue: 'Yashobhoomi (IICC) – Hall 1A+B', date: '2026-07-24',
    dateLabel: '24–26 Jul 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-delhi/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00–11:10' },
      { day: 1, category: 'Men Pro', time: '11:50–13:10' },
      { day: 1, category: 'Women Pro', time: '13:40–13:50' },
      { day: 1, category: 'Doubles Men', time: '14:10–16:30' },
      { day: 1, category: 'Doubles Women', time: '17:00–17:20' },
      { day: 1, category: 'Women Open', time: '17:30–18:10' },
      { day: 1, category: 'Doubles Mixed', time: '18:40–19:50' },
      { day: 2, category: 'Men Open', time: '08:00–15:20' },
      { day: 2, category: 'Doubles Mixed', time: '16:00–18:20' },
      { day: 2, category: 'Doubles Women Pro', time: '18:40' },
      { day: 2, category: 'Doubles Men Pro', time: '19:10–20:10' },
      { day: 3, category: 'Doubles Women', time: '08:00–09:30' },
      { day: 3, category: 'Women Open', time: '09:50–13:00' },
      { day: 3, category: 'Doubles Men', time: '13:30–19:00' },
      { day: 3, category: 'Relay Men', time: '19:30' },
      { day: 3, category: 'Relay Mixed', time: '19:40–19:55' },
      { day: 3, category: 'Relay Women', time: '20:05–20:10' },
    ],
  },
  {
    id: 's10-chengdu',
    city: 'Chengdu', country: 'China', flag: '🇨🇳',
    venue: 'Chengdu Century City New Intl Convention & Exhibition Centre', date: '2026-08-01',
    dateLabel: '1–2 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-chengdu/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-istanbul',
    city: 'Istanbul', country: 'Turkey', flag: '🇹🇷',
    venue: 'Istanbul Fuar Merkezi (IFM)', date: '2026-08-01',
    dateLabel: '1–2 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-istanbul/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '10:00–13:50' },
      { day: 1, category: 'Doubles Women Pro', time: '14:10–14:30' },
      { day: 1, category: 'Women Pro', time: '14:40–15:00' },
      { day: 1, category: 'Doubles Mixed', time: '15:20–17:50' },
      { day: 1, category: 'Doubles Men Pro', time: '18:20–19:10' },
      { day: 1, category: 'Men Pro', time: '19:20–20:30' },
      { day: 2, category: 'Doubles Women', time: '10:00–11:50' },
      { day: 2, category: 'Women Open', time: '12:10–14:50' },
      { day: 2, category: 'Doubles Men', time: '15:20–18:10' },
      { day: 2, category: 'Relay Men', time: '18:40–18:50' },
      { day: 2, category: 'Relay Mixed', time: '19:00–19:10' },
      { day: 2, category: 'Relay Women', time: '19:20–19:30' },
    ],
  },
  {
    id: 's10-chiba',
    city: 'Chiba', country: 'Japan', flag: '🇯🇵',
    venue: 'Makuhari Messe', date: '2026-08-06',
    dateLabel: '6–9 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-chiba/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-bangkok',
    city: 'Bangkok', country: 'Thailand', flag: '🇹🇭',
    venue: 'Queen Sirikit National Convention Center (QSNCC)', date: '2026-08-13',
    dateLabel: '13–16 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-bangkok-2/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-cape-town',
    city: 'Cape Town', country: 'South Africa', flag: '🇿🇦',
    venue: 'Cape Town International Convention Centre (CTICC)', date: '2026-08-14',
    dateLabel: '14–16 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/virgin-active-hyrox-cape-town-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '07:30–11:30' },
      { day: 1, category: 'Women Pro', time: '12:00–12:30' },
      { day: 1, category: 'Men Pro', time: '13:10–14:10' },
      { day: 1, category: 'Doubles Mixed', time: '14:40–18:40' },
      { day: 1, category: 'Relay Men', time: '19:15–19:20' },
      { day: 1, category: 'Relay Mixed', time: '19:35–19:50' },
      { day: 1, category: 'Relay Women', time: '20:15–20:30' },
      { day: 2, category: 'Doubles Women', time: '07:30–12:20' },
      { day: 2, category: 'Women Open', time: '12:40–15:20' },
      { day: 2, category: 'Doubles Men', time: '16:00–18:50' },
      { day: 2, category: 'Doubles Women Pro', time: '19:10–19:30' },
      { day: 2, category: 'Doubles Men Pro', time: '20:00–20:30' },
      { day: 3, category: 'Doubles Women', time: '07:00–09:50' },
      { day: 3, category: 'Doubles Mixed', time: '10:10–12:20' },
      { day: 3, category: 'Doubles Men', time: '12:30–14:30' },
    ],
  },
  {
    id: 's10-shenzhen',
    city: 'Shenzhen', country: 'China', flag: '🇨🇳',
    venue: 'Shenzhen Convention & Exhibition Center (Futian)', ticketsOnSale: false, date: '2026-08-15',
    dateLabel: '15–16 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-shenzhen/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-perth',
    city: 'Perth', country: 'Australia', flag: '🇦🇺',
    venue: 'Perth Convention & Exhibition Centre (PCEC)', date: '2026-08-21',
    dateLabel: '21–23 Aug 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-perth/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-washington-dc',
    city: 'Washington D.C.', country: 'USA', flag: '🇺🇸',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-03',
    dateLabel: '3–7 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-washington-d-c-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:40' },
      { day: 1, category: 'Doubles Women', time: '13:40' },
      { day: 1, category: 'Women / Adaptive Women', time: '15:40' },
      { day: 1, category: 'Doubles Mixed', time: '18:10' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Men Pro', time: '09:50' },
      { day: 2, category: 'Women Pro', time: '12:30' },
      { day: 2, category: 'Doubles Men', time: '14:00' },
      { day: 2, category: 'Doubles Women', time: '15:40' },
      { day: 2, category: 'Women / Adaptive Women', time: '16:20' },
      { day: 2, category: 'Doubles Mixed', time: '17:50' },
      { day: 2, category: 'Relay Men', time: '19:40' },
      { day: 2, category: 'Relay Mixed', time: '20:00' },
      { day: 2, category: 'Relay Women', time: '20:20' },
      { day: 3, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 3, category: 'Doubles Mixed', time: '12:50' },
      { day: 3, category: 'Doubles Women Pro', time: '17:30' },
      { day: 3, category: 'Doubles Men Pro', time: '19:00' },
      { day: 4, category: 'Doubles Women', time: '08:00' },
      { day: 4, category: 'Women / Adaptive Women', time: '12:20' },
      { day: 4, category: 'Doubles Men', time: '16:10' },
      { day: 5, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 5, category: 'Doubles Men', time: '10:30' },
      { day: 5, category: 'Doubles Women', time: '13:10' },
      { day: 5, category: 'Women / Adaptive Women', time: '15:00' },
      { day: 5, category: 'Doubles Mixed', time: '17:20' },
    ],
  },
  {
    id: 's10-tenerife',
    city: 'Tenerife', country: 'Spain', flag: '🇪🇸',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-04',
    dateLabel: '4–6 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-tenerife/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-acapulco',
    city: 'Acapulco', country: 'Mexico', flag: '🇲🇽',
    venue: 'Mundo Imperial', ticketsOnSale: false, date: '2026-09-05',
    dateLabel: '5–6 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-acapulco/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-athens',
    city: 'Athens', country: 'Greece', flag: '🇬🇷',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-05',
    dateLabel: '5–6 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-athens/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-beijing',
    city: 'Beijing', country: 'China', flag: '🇨🇳',
    venue: 'TBC', date: '2026-09-12',
    dateLabel: '12–13 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-beijing-0912/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-maastricht',
    city: 'Maastricht', country: 'Netherlands', flag: '🇳🇱',
    venue: 'MECC Maastricht', date: '2026-09-17',
    dateLabel: '17–20 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-maastricht/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-mumbai',
    city: 'Mumbai', country: 'India', flag: '🇮🇳',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-17',
    dateLabel: '17–20 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-mumbai/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-salt-lake-city',
    city: 'Salt Lake City', country: 'USA', flag: '🇺🇸',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-18',
    dateLabel: '18–20 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-salt-lake-city-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Men Pro', time: '09:50' },
      { day: 1, category: 'Women Pro', time: '12:30' },
      { day: 1, category: 'Doubles Men', time: '14:00' },
      { day: 1, category: 'Doubles Women', time: '15:40' },
      { day: 1, category: 'Women / Adaptive Women', time: '16:20' },
      { day: 1, category: 'Doubles Mixed', time: '17:50' },
      { day: 1, category: 'Relay Men', time: '19:40' },
      { day: 1, category: 'Relay Mixed', time: '20:00' },
      { day: 1, category: 'Relay Women', time: '20:20' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Doubles Mixed', time: '12:50' },
      { day: 2, category: 'Doubles Women Pro', time: '17:30' },
      { day: 2, category: 'Doubles Men Pro', time: '19:00' },
      { day: 3, category: 'Doubles Women', time: '08:00' },
      { day: 3, category: 'Women / Adaptive Women', time: '11:50' },
      { day: 3, category: 'Doubles Men', time: '15:30' },
    ],
  },
  {
    id: 's10-izmir',
    city: 'İzmir', country: 'Turkey', flag: '🇹🇷',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-19',
    dateLabel: '19–20 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-izmir/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-rome',
    city: 'Rome', country: 'Italy', flag: '🇮🇹',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-24',
    dateLabel: '24–27 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-rome/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:50' },
      { day: 1, category: 'Doubles Women', time: '13:20' },
      { day: 1, category: 'Women Open', time: '15:10' },
      { day: 1, category: 'Doubles Mixed', time: '17:20' },
      { day: 2, category: 'Men Open', time: '08:00' },
      { day: 2, category: 'Doubles Men', time: '10:50' },
      { day: 2, category: 'Doubles Women', time: '13:20' },
      { day: 2, category: 'Women Open', time: '15:10' },
      { day: 2, category: 'Doubles Mixed', time: '17:20' },
      { day: 3, category: 'Men Open', time: '08:00' },
      { day: 3, category: 'Men Pro', time: '10:40' },
      { day: 3, category: 'Women Pro', time: '12:50' },
      { day: 3, category: 'Doubles Men', time: '13:30' },
      { day: 3, category: 'Doubles Women', time: '15:20' },
      { day: 3, category: 'Women Open', time: '16:30' },
      { day: 3, category: 'Doubles Mixed', time: '18:00' },
      { day: 3, category: 'Relay Men', time: '19:40' },
      { day: 3, category: 'Relay Mixed', time: '19:55' },
      { day: 3, category: 'Relay Women', time: '20:15' },
      { day: 4, category: 'Men Open', time: '08:00' },
      { day: 4, category: 'Doubles Mixed', time: '13:00' },
      { day: 4, category: 'Doubles Women Pro', time: '18:20' },
      { day: 4, category: 'Doubles Men Pro', time: '19:20' },
      { day: 5, category: 'Doubles Women', time: '08:00' },
      { day: 5, category: 'Women Open', time: '12:00' },
      { day: 5, category: 'Doubles Men', time: '15:10' },
    ],
  },
  {
    id: 's10-oslo',
    city: 'Oslo', country: 'Norway', flag: '🇳🇴',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-25',
    dateLabel: '25–27 Sep 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-oslo/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-bordeaux',
    city: 'Bordeaux', country: 'France', flag: '🇫🇷',
    venue: 'TBC', ticketsOnSale: true, date: '2026-09-30',
    dateLabel: '30 Sep – 4 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-bordeaux-s26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '11:00' },
      { day: 1, category: 'Doubles Women', time: '13:50' },
      { day: 1, category: 'Women Open', time: '15:50' },
      { day: 1, category: 'Doubles Mixed', time: '18:10' },
      { day: 2, category: 'Men Open', time: '08:00' },
      { day: 2, category: 'Doubles Men', time: '10:50' },
      { day: 2, category: 'Doubles Women', time: '13:50' },
      { day: 2, category: 'Women Open', time: '15:50' },
      { day: 2, category: 'Doubles Mixed', time: '18:10' },
      { day: 3, category: 'Men Open', time: '08:00' },
      { day: 3, category: 'Men Pro', time: '09:40' },
      { day: 3, category: 'Women Pro', time: '12:40' },
      { day: 3, category: 'Doubles Men', time: '13:50' },
      { day: 3, category: 'Doubles Women', time: '15:50' },
      { day: 3, category: 'Women Open', time: '16:10' },
      { day: 3, category: 'Doubles Mixed', time: '17:40' },
      { day: 3, category: 'Relay Men', time: '19:30' },
      { day: 3, category: 'Relay Mixed', time: '19:50' },
      { day: 3, category: 'Relay Women', time: '20:10' },
      { day: 4, category: 'Men Open', time: '08:00' },
      { day: 4, category: 'Doubles Mixed', time: '12:50' },
      { day: 4, category: 'Doubles Women Pro', time: '17:40' },
      { day: 4, category: 'Doubles Men Pro', time: '19:00' },
      { day: 5, category: 'Doubles Women', time: '08:00' },
      { day: 5, category: 'Women Open', time: '12:10' },
      { day: 5, category: 'Doubles Men', time: '15:40' },
    ],
  },
  {
    id: 's10-karlsruhe',
    city: 'Karlsruhe', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Karlsruhe', date: '2026-10-01',
    dateLabel: '1–4 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-karlsruhe/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-toronto',
    city: 'Toronto', country: 'Canada', flag: '🇨🇦',
    venue: 'Enercare Centre', date: '2026-10-01',
    dateLabel: '1–4 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/goodlife-hyrox-toronto-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:50' },
      { day: 1, category: 'Doubles Women', time: '13:30' },
      { day: 1, category: 'Women / Adaptive Women', time: '16:00' },
      { day: 1, category: 'Doubles Mixed', time: '18:20' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Men Pro', time: '09:40' },
      { day: 2, category: 'Women Pro', time: '12:00' },
      { day: 2, category: 'Doubles Men', time: '13:20' },
      { day: 2, category: 'Doubles Women', time: '14:50' },
      { day: 2, category: 'Women / Adaptive Women', time: '16:20' },
      { day: 2, category: 'Doubles Mixed', time: '18:00' },
      { day: 2, category: 'Relay Men', time: '19:40' },
      { day: 2, category: 'Relay Mixed', time: '20:00' },
      { day: 2, category: 'Relay Women', time: '20:20' },
      { day: 3, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 3, category: 'Doubles Mixed', time: '13:20' },
      { day: 3, category: 'Doubles Women Pro', time: '17:20' },
      { day: 3, category: 'Doubles Men Pro', time: '19:00' },
      { day: 4, category: 'Doubles Women', time: '08:00' },
      { day: 4, category: 'Women / Adaptive Women', time: '12:20' },
      { day: 4, category: 'Doubles Men', time: '15:30' },
    ],
  },
  {
    id: 's10-boston',
    city: 'Boston', country: 'USA', flag: '🇺🇸',
    venue: 'TBC', ticketsOnSale: true, date: '2026-10-08',
    dateLabel: '8–11 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hwpo-hyrox-boston-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '09:50' },
      { day: 1, category: 'Doubles Women', time: '12:40' },
      { day: 1, category: 'Women / Adaptive Women', time: '15:40' },
      { day: 1, category: 'Doubles Mixed', time: '18:50' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Men Pro', time: '09:30' },
      { day: 2, category: 'Women Pro', time: '11:30' },
      { day: 2, category: 'Doubles Men', time: '12:40' },
      { day: 2, category: 'Doubles Women', time: '14:10' },
      { day: 2, category: 'Women / Adaptive Women', time: '15:50' },
      { day: 2, category: 'Doubles Mixed', time: '18:00' },
      { day: 2, category: 'Relay Men', time: '19:30' },
      { day: 2, category: 'Relay Mixed', time: '19:50' },
      { day: 2, category: 'Relay Women', time: '20:15' },
      { day: 3, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 3, category: 'Doubles Mixed', time: '12:50' },
      { day: 3, category: 'Doubles Women Pro', time: '17:50' },
      { day: 3, category: 'Doubles Men Pro', time: '19:10' },
      { day: 4, category: 'Doubles Women', time: '08:00' },
      { day: 4, category: 'Women / Adaptive Women', time: '11:00' },
      { day: 4, category: 'Doubles Men', time: '13:10' },
    ],
  },
  {
    id: 's10-geneva',
    city: 'Geneva', country: 'Switzerland', flag: '🇨🇭',
    venue: 'Palexpo', date: '2026-10-09',
    dateLabel: '9–11 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-geneva/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-gdansk',
    city: 'Gdańsk', country: 'Poland', flag: '🇵🇱',
    venue: 'Ergo Arena', date: '2026-10-10',
    dateLabel: '10–11 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-gdansk/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-valencia',
    city: 'Valencia', country: 'Spain', flag: '🇪🇸',
    venue: 'Feria Valencia', date: '2026-10-16',
    dateLabel: '16–18 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-valencia/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-sao-paulo',
    city: 'São Paulo', country: 'Brazil', flag: '🇧🇷',
    venue: 'TBC', ticketsOnSale: true, date: '2026-10-17',
    dateLabel: '17 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-sao-paulo-2/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-tampa',
    city: 'Tampa', country: 'USA', flag: '🇺🇸',
    venue: 'TBC', ticketsOnSale: true, date: '2026-10-23',
    dateLabel: '23–25 Oct 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-tampa/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Men Pro', time: '09:40' },
      { day: 1, category: 'Women Pro', time: '12:20' },
      { day: 1, category: 'Doubles Mixed', time: '12:40' },
      { day: 1, category: 'Doubles Men', time: '15:10' },
      { day: 1, category: 'Doubles Women', time: '16:50' },
      { day: 1, category: 'Women / Adaptive Women', time: '18:10' },
      { day: 1, category: 'Relay Men', time: '19:40' },
      { day: 1, category: 'Relay Women', time: '20:20' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Doubles Mixed', time: '12:40' },
      { day: 2, category: 'Doubles Women Pro', time: '17:30' },
      { day: 2, category: 'Doubles Men Pro', time: '18:50' },
      { day: 3, category: 'Doubles Women', time: '08:00' },
      { day: 3, category: 'Women / Adaptive Women', time: '12:10' },
      { day: 3, category: 'Doubles Men', time: '15:40' },
    ],
  },
  {
    id: 's10-birmingham',
    city: 'Birmingham', country: 'UK', flag: '🇬🇧',
    venue: 'NEC Birmingham', date: '2026-10-27',
    dateLabel: '27 Oct – 1 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-birmingham/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-hamburg',
    city: 'Hamburg', country: 'Germany', flag: '🇩🇪',
    venue: 'Hamburg Messe', date: '2026-10-28',
    dateLabel: '28 Oct – 1 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/intersport-hyrox-hamburg/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-nice',
    city: 'Nice', country: 'France', flag: '🇫🇷',
    venue: 'Acropolis Nice', date: '2026-10-29',
    dateLabel: '29 Oct – 1 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-nice-s26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:50' },
      { day: 1, category: 'Doubles Women', time: '13:30' },
      { day: 1, category: 'Women Open', time: '15:40' },
      { day: 1, category: 'Doubles Mixed', time: '17:50' },
      { day: 2, category: 'Men Open', time: '08:00' },
      { day: 2, category: 'Men Pro', time: '10:10' },
      { day: 2, category: 'Women Pro', time: '12:40' },
      { day: 2, category: 'Doubles Men', time: '14:10' },
      { day: 2, category: 'Doubles Women', time: '15:40' },
      { day: 2, category: 'Women Open', time: '16:40' },
      { day: 2, category: 'Doubles Mixed', time: '17:50' },
      { day: 2, category: 'Relay Men', time: '19:40' },
      { day: 2, category: 'Relay Mixed', time: '20:00' },
      { day: 2, category: 'Relay Women', time: '20:20' },
      { day: 3, category: 'Men Open', time: '08:00' },
      { day: 3, category: 'Doubles Mixed', time: '13:00' },
      { day: 3, category: 'Doubles Women Pro', time: '16:50' },
      { day: 3, category: 'Doubles Men Pro', time: '18:10' },
      { day: 4, category: 'Doubles Women', time: '08:00' },
      { day: 4, category: 'Women Open', time: '12:00' },
      { day: 4, category: 'Doubles Men', time: '16:00' },
    ],
  },
  {
    id: 's10-mexico-city',
    city: 'Mexico City', country: 'Mexico', flag: '🇲🇽',
    venue: 'TBC', date: '2026-10-30',
    dateLabel: '30 Oct – 1 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-mexico-city/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-shanghai',
    city: 'Shanghai', country: 'China', flag: '🇨🇳',
    venue: 'TBC', date: '2026-10-31',
    dateLabel: '31 Oct – 1 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-shanghai-1031/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-dublin',
    city: 'Dublin', country: 'Ireland', flag: '🇮🇪',
    venue: 'TBC', date: '2026-11-11',
    dateLabel: '11–15 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-dublin/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-dusseldorf',
    city: 'Düsseldorf', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Düsseldorf', ticketsOnSale: false, date: '2026-11-11',
    dateLabel: '11–15 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-dusseldorf/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-barcelona',
    city: 'Barcelona', country: 'Spain', flag: '🇪🇸',
    venue: 'Fira Barcelona', date: '2026-11-12',
    dateLabel: '12–15 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-barcelona-2/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-denver',
    city: 'Denver', country: 'USA', flag: '🇺🇸',
    venue: 'Colorado Convention Center', date: '2026-11-12',
    dateLabel: '12–15 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-denver/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Doubles Women', time: '12:20' },
      { day: 1, category: 'Women / Adaptive Women', time: '15:10' },
      { day: 1, category: 'Doubles Mixed', time: '18:10' },
      { day: 2, category: 'Women Pro', time: '11:50' },
      { day: 2, category: 'Doubles Mixed', time: '14:30' },
      { day: 2, category: 'Doubles Women', time: '16:20' },
      { day: 2, category: 'Women / Adaptive Women', time: '17:30' },
      { day: 2, category: 'Relay Men', time: '19:40' },
      { day: 2, category: 'Relay Mixed', time: '20:00' },
      { day: 2, category: 'Relay Women', time: '20:20' },
      { day: 3, category: 'Doubles Mixed', time: '12:50' },
      { day: 3, category: 'Doubles Women Pro', time: '17:20' },
      { day: 3, category: 'Doubles Men Pro', time: '18:50' },
      { day: 4, category: 'Women / Adaptive Women', time: '12:40' },
      { day: 4, category: 'Doubles Men', time: '16:20' },
    ],
  },
  {
    id: 's10-seoul',
    city: 'Seoul', country: 'South Korea', flag: '🇰🇷',
    venue: 'TBC', ticketsOnSale: true, date: '2026-11-14',
    dateLabel: '14–15 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-seoul/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-dallas',
    city: 'Dallas', country: 'USA', flag: '🇺🇸',
    venue: 'Kay Bailey Hutchison Convention Center', date: '2026-11-18',
    dateLabel: '18–22 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-dallas/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:00' },
      { day: 1, category: 'Doubles Women', time: '12:20' },
      { day: 1, category: 'Women / Adaptive Women', time: '15:00' },
      { day: 1, category: 'Doubles Mixed', time: '18:10' },
      { day: 2, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 2, category: 'Doubles Men', time: '10:00' },
      { day: 2, category: 'Doubles Women', time: '12:20' },
      { day: 2, category: 'Women / Adaptive Women', time: '15:00' },
      { day: 2, category: 'Doubles Mixed', time: '18:10' },
      { day: 3, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 3, category: 'Men Pro', time: '09:40' },
      { day: 3, category: 'Women Pro', time: '12:10' },
      { day: 3, category: 'Doubles Men', time: '14:00' },
      { day: 3, category: 'Doubles Women', time: '15:40' },
      { day: 3, category: 'Women / Adaptive Women', time: '16:20' },
      { day: 3, category: 'Doubles Mixed', time: '17:50' },
      { day: 3, category: 'Relay Men', time: '19:40' },
      { day: 3, category: 'Relay Mixed', time: '20:00' },
      { day: 3, category: 'Relay Women', time: '20:20' },
      { day: 4, category: 'Men / Adaptive Men', time: '08:00' },
      { day: 4, category: 'Doubles Mixed', time: '12:50' },
      { day: 4, category: 'Doubles Women Pro', time: '17:30' },
      { day: 4, category: 'Doubles Men Pro', time: '19:00' },
      { day: 5, category: 'Doubles Women', time: '08:00' },
      { day: 5, category: 'Women / Adaptive Women', time: '13:20' },
      { day: 5, category: 'Doubles Men', time: '17:20' },
    ],
  },
  {
    id: 's10-poznan',
    city: 'Poznań', country: 'Poland', flag: '🇵🇱',
    venue: 'MTP Poznań', date: '2026-11-20',
    dateLabel: '20–22 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-poznan/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-guangzhou',
    city: 'Guangzhou', country: 'China', flag: '🇨🇳',
    venue: 'TBC', date: '2026-11-21',
    dateLabel: '21–22 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-guangzhou/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-rio',
    city: 'Rio de Janeiro', country: 'Brazil', flag: '🇧🇷',
    venue: 'TBC', date: '2026-11-21',
    dateLabel: '21 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-rio-de-janeiro/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-utrecht',
    city: 'Utrecht', country: 'Netherlands', flag: '🇳🇱',
    venue: 'Jaarbeurs Utrecht', date: '2026-11-26',
    dateLabel: '26–30 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-utrecht/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: true,
    waves: [
      { day: 1, category: 'Men Open', time: '08:00' },
      { day: 1, category: 'Doubles Men', time: '10:30' },
      { day: 1, category: 'Doubles Women', time: '13:20' },
      { day: 1, category: 'Women Open', time: '15:50' },
      { day: 1, category: 'Doubles Mixed', time: '18:10' },
      { day: 2, category: 'Men Open', time: '08:00' },
      { day: 2, category: 'Men Pro', time: '09:40' },
      { day: 2, category: 'Doubles Mixed', time: '12:50' },
      { day: 2, category: 'Women Pro', time: '14:30' },
      { day: 2, category: 'Doubles Women', time: '15:40' },
      { day: 2, category: 'Relay Men', time: '19:40' },
      { day: 2, category: 'Relay Mixed', time: '20:00' },
      { day: 2, category: 'Relay Women', time: '20:20' },
      { day: 3, category: 'Men Open', time: '08:00' },
      { day: 3, category: 'Doubles Mixed', time: '12:40' },
      { day: 3, category: 'Doubles Women Pro', time: '17:10' },
      { day: 3, category: 'Doubles Men Pro', time: '18:50' },
      { day: 4, category: 'Doubles Women', time: '08:00' },
      { day: 4, category: 'Women Open', time: '12:40' },
      { day: 4, category: 'Doubles Men', time: '16:30' },
      { day: 5, category: 'Men Open', time: '08:00' },
      { day: 5, category: 'Doubles Men', time: '10:20' },
      { day: 5, category: 'Doubles Women', time: '12:50' },
      { day: 5, category: 'Women Open', time: '15:00' },
      { day: 5, category: 'Doubles Mixed', time: '17:20' },
    ],
  },
  {
    id: 's10-singapore',
    city: 'Singapore', country: 'Singapore', flag: '🇸🇬',
    venue: 'Singapore Expo', date: '2026-11-27',
    dateLabel: '27–29 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/aia-hyrox-singapore/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-johannesburg',
    city: 'Johannesburg', country: 'South Africa', flag: '🇿🇦',
    venue: 'TBC', date: '2026-11-28',
    dateLabel: '28–29 Nov 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/virgin-active-hyrox-johannesburg-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-london',
    city: 'London', country: 'UK', flag: '🇬🇧',
    venue: 'ExCeL London', ticketsOnSale: false, date: '2026-12-02',
    dateLabel: '2–6 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-london-excel/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-anaheim',
    city: 'Anaheim', country: 'USA', flag: '🇺🇸',
    venue: 'Anaheim Convention Center', ticketsOnSale: false, date: '2026-12-04',
    dateLabel: '4–6 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-anaheim-26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-milan',
    city: 'Milan', country: 'Italy', flag: '🇮🇹',
    venue: 'Allianz MiCo', ticketsOnSale: false, date: '2026-12-05',
    dateLabel: '5–6 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-milan/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-sanya',
    city: 'Sanya', country: 'China', flag: '🇨🇳',
    venue: 'TBC', date: '2026-12-05',
    dateLabel: '5–6 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/30454/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-stockholm',
    city: 'Stockholm', country: 'Sweden', flag: '🇸🇪',
    venue: 'Stockholm Arena', date: '2026-12-10',
    dateLabel: '10–13 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/intersport-hyrox-stockholm-arena/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-frankfurt',
    city: 'Frankfurt', country: 'Germany', flag: '🇩🇪',
    venue: 'Messe Frankfurt', ticketsOnSale: false, date: '2026-12-10',
    dateLabel: '10–13 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/fitness-first-hyrox-frankfurt/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-nashville',
    city: 'Nashville', country: 'USA', flag: '🇺🇸',
    venue: 'Music City Center', ticketsOnSale: false, date: '2026-12-10',
    dateLabel: '10–13 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-nashville/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-paris',
    city: 'Paris', country: 'France', flag: '🇫🇷',
    venue: 'Paris Nord Villepinte', ticketsOnSale: false, date: '2026-12-12',
    dateLabel: '12–20 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-paris-s26-27/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-gent',
    city: 'Gent', country: 'Belgium', flag: '🇧🇪',
    venue: 'Flanders Expo', ticketsOnSale: false, date: '2026-12-17',
    dateLabel: '17–20 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-gent/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-helsinki',
    city: 'Helsinki', country: 'Finland', flag: '🇫🇮',
    venue: 'TBC', date: '2026-12-18',
    dateLabel: '18–20 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-helsinki-2/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-vancouver',
    city: 'Vancouver', country: 'Canada', flag: '🇨🇦',
    venue: 'Vancouver Convention Centre', ticketsOnSale: false, date: '2026-12-18',
    dateLabel: '18–20 Dec 2026', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-vancouver/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
  {
    id: 's10-melbourne',
    city: 'Melbourne', country: 'Australia', flag: '🇦🇺',
    venue: 'Melbourne Convention & Exhibition Centre', ticketsOnSale: false, date: '2027-01-01',
    dateLabel: 'Date coming soon', status: 'upcoming', isChampionship: false,
    venueUrl: 'https://hyrox.com/event/hyrox-melbourne/', mapImg: null, mapImgDirect: null,
    wavesConfirmed: false, waves: [],
  },
];

// ─── Lookup by season number ─────────────────────────────────────────────────
const HYROX_SEASONS = {
  10: { label: 'Season 10', years: '2026 – 27', events: HYROX_S10_EVENTS },
  9: { label: 'Season 9', years: '2025 – 26', events: HYROX_EVENTS },
  8: { label: 'Season 8', years: '2024 – 25', events: HYROX_S8_EVENTS },
  7: { label: 'Season 7', years: '2023 – 24', events: HYROX_S7_EVENTS },
};
