// ─── AUTO-GENERATED by scripts/scrape-events.js ─────────────────────────────
// Source of truth: data/sN/events.json  ·  Do not edit this file manually.
// Run: cd scripts && node scrape-events.js
// Generated: 2026-06-16T13:02:29.523Z

const HYROX_S7_EVENTS = [];

const HYROX_S8_EVENTS = [];

const HYROX_EVENTS = [];  // Season 9

const HYROX_S10_EVENTS = [];

const HYROX_SEASONS = {
  10: { label: 'Season 10', years: '2026 – 27', events: HYROX_S10_EVENTS },
  9: { label: 'Season 9', years: '2025 – 26', events: HYROX_EVENTS },
  8: { label: 'Season 8', years: '2024 – 25', events: HYROX_S8_EVENTS },
  7: { label: 'Season 7', years: '2023 – 24', events: HYROX_S7_EVENTS },
};
